# Generated by Django 5.0.1 on 2024-01-23 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_checkboxitem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CheckboxItem',
        ),
    ]
