# Generated by Django 5.0.1 on 2024-01-23 15:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_delete_checkboxitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clock', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
