# Generated by Django 5.0.1 on 2024-01-23 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0005_newview'),
    ]

    operations = [
        migrations.AddField(
            model_name='newview',
            name='title',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
    ]
