# Generated by Django 5.0.1 on 2024-01-23 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0006_newview_title'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NewView',
        ),
    ]
